# This workflow will install a prebuilt Ruby version, install dependencies, and run tests.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]    
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup chromedriver
        uses: nanasess/setup-chromedriver@v2
      - name: Start chromedriver
        run: |
             export DISPLAY=:99
             chromedriver --url-base=/wd/hub &
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:          
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Set up database schema
        run: rake db:test:prepare
      - name: Run tests
        run: bundle exec rspec spec
